<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DevendraS-130398" failures="1" tests="4" name="com.crm.qa.testcases.NewCartcreationPageTest" time="46.387" errors="0" timestamp="12 Mar 2024 12:21:48 GMT" skipped="0">
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="verifyhomepage" time="7.939"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="verifyCartListingpage" time="10.590"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="ClickonNewCartButton" time="13.727"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="CartCreationPossitiveflow" time="14.131">
    <failure message="expected [https://qaspicexpress.kargo360tech.com/cart/list] but found [https://qaspicexpress.kargo360tech.com/cart/create]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/cart/list] but found [https://qaspicexpress.kargo360tech.com/cart/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewCartcreationPageTest.CartCreationPossitiveflow(NewCartcreationPageTest.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CartCreationPossitiveflow -->
</testsuite> <!-- com.crm.qa.testcases.NewCartcreationPageTest -->
